#!/usr/bin/python2.7
from hosted import device, node, config, time, threading
config.restart_on_update()

device.gpio.monitor(config.pin_16)
device.gpio.monitor(config.pin_17)
device.gpio.monitor(config.pin_18)
device.gpio.monitor(config.pin_19)

def handle_pin(pin, state):
    command = '1' if state == 1 else '0'
    print("pin {} state: {}".format(pin, command))
    node.send('/state/{}'.format(pin), command)  # Sending the command as the second argument

def gpio_poll_loop():
    for pin, state in device.gpio.poll_forever():
        if pin in [config.pin_16, config.pin_17, config.pin_18, config.pin_19]:
            threading.Thread(target=handle_pin, args=(pin, state)).start()

# Start the GPIO polling loop in a separate thread
gpio_poll_thread = threading.Thread(target=gpio_poll_loop)
gpio_poll_thread.start()

