#!/usr/bin/python2.7
from hosted import device, node, config, time, threading
config.restart_on_update()

device.gpio.monitor(config.pin_16)
device.gpio.monitor(config.pin_17)
device.gpio.monitor(config.pin_18)
device.gpio.monitor(config.pin_19)

def send_command(pin, state):
    node.send('/state/{}'.format(pin), str(state))

def handle_pin(pin, state):
    if state == 1:
        print("pin {} touched".format(pin))
        send_command(pin, 1)
        time.sleep(5)  # Adjust the sleep time as needed
        send_command(pin, 0)
        print("pin {} touched state 0".format(pin))

def gpio_poll_loop():
    for pin, state in device.gpio.poll_forever():
        if pin in [config.pin_16, config.pin_17, config.pin_18, config.pin_19]:
            threading.Thread(target=handle_pin, args=(pin, state)).start()

# Start the GPIO polling loop in a separate thread
gpio_poll_thread = threading.Thread(target=gpio_poll_loop)
gpio_poll_thread.start()

